### PR TITLE
Feature/metadata timestamps

### PR DESCRIPTION
**Pull request by jrandall**
Adds the ability for baton-metaquery to search on metadata creation and modified timestamps in addition to the creation and modified timestamps for the data/collection itself. 

Adds fields to the JSON under `timestamps` called `metadata_created` and `metadata_modified` which work in a similar way to `created` and `modified`, except they operate on the `META_DATA_*` and `META_COLL_*` timestamps.

### CODE REVIEW

**Comment by keithj** [comment]
Looks good. I'd like to check that iRODS' behaviour is sufficient for your purposes; the metadata timestamp is the time at which an unique AVU tuple was added to the ICAT, not the time at which that AVU was associated with a data object or collection. Orphaned AVUs are not garbage collected from the ICAT, so the timestamps for their original insertion will be reported if they get re-associated with a data object in the future.

**Comment by jrandall** [comment]
Huh. That's -- interesting? I guess timestamps for when metadata is
associated to a data object are not available at all, or are they reflected
in the data object modification time?

**Comment by jrandall** [comment]
Colin is working on an related `--meta-timestamp` option for reporting the
timestamps on metadata, but if it is a global timestamp of a unique AVU
rather than an AVU in association with a data object or collection, it
wouldn't seem that useful (to anyone! what would be the point?).

**Comment by keithj** [comment]
I agree, the behaviour is "interesting". I've tested your pull request to be sure that I'm correct about this. I inserted some CRAM files into a test iRODS yesterday. They all have the AVU `lane == 1`

````
jq -n '{"avus":[{"attribute":"lane","value":"1"}], "timestamps":[{"meta_modified":"2015-09-24T00:00:00","operator":"n>="}, {"meta_modified":"2015-09-30T00:00:00","operator":"n<"}]}'|./src/baton-metaquery 
[]
````

However, when I set the time window back to 2013...

````
jq -n '{"avus":[{"attribute":"lane","value":"1"}], "timestamps":[{"meta_modified":"2013-09-01T00:00:00","operator":"n>="}, {"meta_modified":"2015-09-30T00:00:00","operator":"n<"}]}'|./src/baton-metaquery | jq . | wc -l
258
````

This is because the `lane == 1` AVU was inserted way back:
imeta ls -ld 17670_1#0.cram

... 

attribute: lane
value: 1
units: 
time set: 2014-05-06.09:28:33
````

All the CRAM files are returned because they have the "same" date. More perplexing is that there is a link table between AVU and data object that _does_ have it's own timestamp dating the link! I'm not sure that this is accessible through the pseudo-SQL. I'm having a look - it may be that changing a couple of lines in the query code will allow it to use the useful value instead.

**Comment by keithj** [comment]
I think that the table with useful values is `r_objt_metamap`. Unfortunately, it doesn't seem to be exposed in the genQuery API. Not in a way that I can discover, anyway.

**Comment by jrandall** [comment]
I've just done some tests to confirm the behaviour is as you describe (the meta data timestamps are about when the unique AVU entry was added, not when it is linked to a particular object). You can verify this with the icommands, using `iquest` to get the metadata timestamps:

```
$ imkdir /Sanger1/home/jr17/test-mdtime
$ touch foo
$ touch bar
$ iput foo /Sanger1/home/jr17/test-mdtime/foo
$ iput bar /Sanger1/home/jr17/test-mdtime/bar
$ imeta add -d /Sanger1/home/jr17/test-mdtime/foo a 1
$ imeta ls -d /Sanger1/home/jr17/test-mdtime/foo
AVUs defined for dataObj /Sanger1/home/jr17/test-mdtime/foo:
attribute: a
value: 1
units:
$ iquest -z Sanger1 --no-page "%s %s" "SELECT META_DATA_CREATE_TIME,META_DATA_MODIFY_TIME WHERE COLL_NAME = '/Sanger1/home/jr17/test-mdtime' AND DATA_NAME = 'foo'"
Zone is Sanger1
01443185708 01443185708
$ imeta add -d /Sanger1/home/jr17/test-mdtime/bar a 1
$ iquest -z Sanger1 --no-page "%s %s" "SELECT META_DATA_CREATE_TIME,META_DATA_MODIFY_TIME WHERE COLL_NAME = '/Sanger1/home/jr17/test-mdtime' AND DATA_NAME = 'bar'"
Zone is Sanger1
01443185708 01443185708
$ imeta mod -d /Sanger1/home/jr17/test-mdtime/bar a 1 n:a v:2
$ iquest -z Sanger1 --no-page "%s %s" "SELECT META_DATA_CREATE_TIME,META_DATA_MODIFY_TIME WHERE COLL_NAME = '/Sanger1/home/jr17/test-mdtime' AND DATA_NAME = 'bar'"
Zone is Sanger1
01443186004 01443186004
$ iquest -z Sanger1 --no-page "%s %s" "SELECT META_DATA_CREATE_TIME,META_DATA_MODIFY_TIME WHERE COLL_NAME = '/Sanger1/home/jr17/test-mdtime' AND DATA_NAME = 'foo'"
Zone is Sanger1
01443185708 01443185708
$ imeta mod -d /Sanger1/home/jr17/test-mdtime/foo a 1 n:a v:3
$ iquest -z Sanger1 --no-page "%s %s" "SELECT META_DATA_CREATE_TIME,META_DATA_MODIFY_TIME WHERE COLL_NAME = '/Sanger1/home/jr17/test-mdtime' AND DATA_NAME = 'foo'"
Zone is Sanger1
01443186042 01443186042
$ imeta set -d /Sanger1/home/jr17/test-mdtime/foo a 1
$ iquest -z Sanger1 --no-page "%s %s" "SELECT META_DATA_CREATE_TIME,META_DATA_MODIFY_TIME WHERE COLL_NAME = '/Sanger1/home/jr17/test-mdtime' AND DATA_NAME = 'foo'"
Zone is Sanger1
01443185708 01443185708
$ imeta set -d /Sanger1/home/jr17/test-mdtime/foo a 4
$ iquest -z Sanger1 --no-page "%s %s" "SELECT META_DATA_CREATE_TIME,META_DATA_MODIFY_TIME WHERE COLL_NAME = '/Sanger1/home/jr17/test-mdtime' AND DATA_NAME = 'foo'"
Zone is Sanger1
01443186093 01443186093
```

How completely useless is that information? What were they thinking? Among other things that makes it pointless is that there does not appear to be any way to make `META_DATA_CREATE_TIME` and `META_DATA_MODIFY_TIME` have different values (because one never actually "modifies" a value in the AVU table - the new value is simply inserted as a new entry in the table). 

Obviously the interesting timestamps would be the ones that map AVU entries to objects/collections. It sounds like you are saying that the database has that information in the `r_objt_metamap` table but that it isn't exposed via the API for some insane reason. I'm looking through the iRODS source as well, but so far don't find any way of accessing it. 

Can we please bring this up with the iRODS developers? This is a huge feature that is lacking, and effectively prevents us from knowing when metadata has been changed except by basically dumping the entire metadata database and comparing it with previous values.

**Comment by jrandall** [comment]
Filed as an issue with iRODS: https://github.com/irods/irods/issues/2905

**Comment by jrandall** [comment]
I think this feature is of limited usefulness, at least for us, because we now have the specific (SQL) queries that return the timestamps that we are actually interested in (i.e. the ones from the metamap table rather than the metadata table itself). 

Closing.

**Comment by jrandall** [comment]
In case anyone finds this and is interested in installing specific queries to get at this timestamp data, you may be interested in the set of specific queries we are using as an alternative to this feature: https://github.com/wtsi-hgi/cookie-monster/tree/develop/resources/specific-queries

**Pull request closed without merging**
